name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v4

      - name: Verificar estructura del proyecto
        run: |
          echo "Proyecto: Sitio-Web-de-Herencia-Cultural-Arequipa"
          ls -la

      - name: Validación básica
        run: |
          echo "La página web está lista para su revisión."
